version: '3'


services:
  psql:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./init.sql:/app-data/docker-entrypoint-initdb.d/schema.sql
      - ./init.sql:/app-data/docker-entrypoint-initdb.d/data.sql

#  webapp:
#    image: 'webapp'
#
#    volumes:
#      - '.:/app-web'
#      - '/app-web/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true

  apiapp:
    image: 'apiapp'
    links:
      - psql # app see psql, psql is domain now
    ports:
      - "8095"

#  nginx:
#    image: nginx
#    volumes:
#      - ./templates:/etc/nginx/templates
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=gigglingpenguin.me
#      - NGINX_PORT=80

