version: '3'


services:
  psql:
    image: 'bitnami/postgresql:latest'
    env_file:
      - app-data/database.env # configure postgres. Password etc
    volumes:
      - /docker-entrypoint-initdb.d

  # psql -h psql -p 5432 -U test -d database

  webapp:
    container_name: webapp
    build:
      context: ./app-web/
      dockerfile: Dockerfile
    volumes:
      - '.:/app-web'
      - '/app-web/node_modules'
    ports:
      - 3000:3000 # double ip means from : to . One ip dsnt works
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # important line


  apiapp:
    container_name: apiapp
    build:
      context: ./app-api
      dockerfile: Dockerfile
    volumes:
      - '.:/app-api/*'
    links:
      - psql # app see psql, psql is domain now
    #ports:
    #  - 8095:8095
    expose: # stay at compose local
      - 8095

  #   https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/nginx.conf
    ports: # go to global
      - 80:80
      - 443:443

