name: Docker Image CI
# https://www.youtube.com/watch?v=09lZdSpeHAk&ab_channel=ThatDevOpsGuy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker
      run: docker-compose up 
