name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker deploy on server
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.SERVER_HOST }}
         username: root
         password: ${{ secrets.SERVER_PSWD }}
         script: |
          echo Hello there
          docker-compose down
          rm SpringRestEdu/ -r f
          git clone https://github.com/watislaf/SpringRestEdu.git
          cd SpringRestEdu/
          docker-compose up --build -d

          
    
