name: Docker Image CI
# https://www.youtube.com/watch?v=09lZdSpeHAk&ab_channel=ThatDevOpsGuy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker deploy on server
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.SERVER_HOST }}
         username: root
         password: ${{ secrets.SERVER_PSWD }}
         script: |
          echo Hello there
          rm SpringRestEdu/ -r -f
          git clone https://github.com/watislaf/SpringRestEdu.git
          cd SpringRestEdu/
          docker-compose down
          docker-compose up --build -d
    - name: Sleep for 80 seconds till server loading
      uses: jakejarvis/wait-action@master
      with:
        time: '80s'
    - name: Check http status code of production site
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["http://tempw.gigglingpenguin.me", "http://tempapi.gigglingpenguin.me"]'
        expected: '[200]'

          
    
